add reviews
Alexandra0707/luxury-yacht-09 pull request #3
Opened 2024-08-09 17:21 UTC by Olya-rar

Добрий вечір!
Поки свої картинки локально підставляла (перед пушем видалила іх), потім після Вашої перевірки вставлю картинки які завантажить Артем.

2024-08-09 17:50 UTC, Alexandra0707 requested changes

2024-08-09 17:50 UTC, Alexandra0707 commented on src/css/reviews.css
> +@media screen and (min-width: 768px) {
навіщо ви повторюєте? Треба перемістити вище у вас вже є такий пункт

2024-08-09 17:50 UTC, Alexandra0707 commented on src/css/reviews.css
> +  gap: 24px;
В мене відстань 32px. Перевірте будь ласка

2024-08-09 17:50 UTC, Alexandra0707 commented on src/partials/reviews.html
> +<section class="container reviews">
container reviews пишеться через " -" ( приклад: container-reviews)

2024-08-09 17:50 UTC, Alexandra0707 commented on src/css/reviews.css
> +    max-width: 376px;
ширина задаеться секціі

2024-08-09 17:50 UTC, Alexandra0707 commented on src/css/reviews.css
> +@media screen and (min-width: 768px) {
непотрібно кожного разу писати @media. Один раз написали і всі класи об"єднали

2024-08-09 17:50 UTC, Alexandra0707 commented on src/css/reviews.css
> +@media screen and (min-width: 1280px) {
непотрібно кожного разу писати @media. Один раз написали і всі класи об"єднали

2024-08-09 17:50 UTC, Alexandra0707 commented on src/css/reviews.css
> +@media screen and (min-width: 1280px) {
непотрібно кожного разу писати @media. Один раз написали і всі класи об"єднали

2024-08-09 17:50 UTC, Alexandra0707 commented on src/css/reviews.css
> +@media screen and (min-width: 1280px) {
непотрібно кожного разу писати @media. Один раз написали і всі класи об"єднали

2024-08-09 17:50 UTC, Alexandra0707 commented on src/css/reviews.css
> +@media screen and (min-width: 1280px) {
непотрібно кожного разу писати @media. Один раз написали і всі класи об"єднали

2024-08-09 17:50 UTC, Alexandra0707 commented on src/css/reviews.css
> +@media screen and (min-width: 768px) {
непотрібно кожного разу писати @media. Один раз написали і всі класи об"єднали

2024-08-09 18:17 UTC, Olya-rar commented on src/partials/reviews.html
> +<section class="container reviews">
Це два різні класи, у CSS вони прописані. Загального контейнера немає для відступів по бокам, тому поки що задала свій.

2024-08-09 18:19 UTC, Olya-rar commented on src/css/reviews.css
> +    max-width: 376px;
Це ширина білих квадратів, а не самої секції.

2024-08-10 15:26 UTC, Alexandra0707 approved these changes

2024-08-10 15:32 UTC, merged