add footer
Alexandra0707/luxury-yacht-09 pull request #5
Opened 2024-08-10 08:07 UTC by Bohdana-Skolzaieva-3101

Привіт Олександра! Майже доробила footer, тільки з позиціонуванням в мене біда ((( От хоть ти трісни не знаю як його розмістити в мобільній версії?! Тож попрошу тебе запитати у ментора, що мені треба переробити чи можливо ти підкажеш.  Дякую

2024-08-10 15:17 UTC, Alexandra0707 requested changes

2024-08-10 15:17 UTC, Alexandra0707 commented on src/css/footer.css
> +.container-footer {
спробуйте добавити  justify-content: center та    align-items: baseline; щоб секція розтягувалась на всю ширину

2024-08-10 15:17 UTC, Alexandra0707 commented on src/css/footer.css
> +  max-width: 355px;
ширина 375

2024-08-10 15:17 UTC, Alexandra0707 commented on src/css/footer.css
> +.footer-icon-item {
іконки у мобільній версії не по центру

2024-08-10 20:22 UTC, Alexandra0707 requested changes

2024-08-10 20:22 UTC, Alexandra0707 commented on src/css/footer.css
відправила видео у Slack

2024-08-11 11:07 UTC, Bohdana-Skolzaieva-3101 commented on src/css/footer.css
> +  max-width: 355px;
чому ширина контейнера у футера має бути 375px? на макеті ж 355px
![footer-mob size](https://github.com/user-attachments/assets/43ea9165-6b18-4688-8963-3ce614ecde0e)

2024-08-11 15:09 UTC, closed without merging