Featuers-rent-yacht
Alexandra0707/luxury-yacht-09 pull request #6
Opened 2024-08-10 15:36 UTC by NataliiaKopychynska

2024-08-10 18:07 UTC, Alexandra0707 requested changes

2024-08-10 18:07 UTC, Alexandra0707 commented on src/css/rent-yacht.css
Видаліть будь ласка фото і пришліть заново я прийму вашу работу.  Я прийму роботу Артема і будемо дивитись що вийде

2024-08-11 11:27 UTC, NataliiaKopychynska commented on src/css/rent-yacht.css
хай він нарешті скине фото і я тоді зміню шлях і видалю 😶‍🌫️

2024-08-11 16:00 UTC, Alexandra0707 requested changes
Я не приймаю фото поки ми не вирішемо що з ними робити

2024-08-11 16:07 UTC, Alexandra0707 approved these changes

2024-08-11 16:07 UTC, merged